language: ruby
rvm:
  - 2.3.4

# Use container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache:
  bundler: true

gemfile:
  - gemfiles/rails_5.1_active_admin_1.0.gemfile
  - gemfiles/rails_5.1_active_admin_1.2.gemfile
  - gemfiles/rails_5.x_active_admin_1.3.gemfile

script: bundle exec rspec
